{
 "title": "Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"aws_sd\",instance=\"dev-prometheus;172.31.93.122\",mode!=\"idle\"}[1m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"dev-prometheus;172.31.93.122\", job=\"aws_sd\"} - node_memory_MemFree_bytes{instance=\"dev-prometheus;172.31.93.122\", job=\"aws_sd\"} - node_memory_Cached_bytes{instance=\"dev-prometheus;172.31.93.122\", job=\"aws_sd\"} - node_memory_Buffers_bytes{instance=\"dev-prometheus;172.31.93.122\", job=\"aws_sd\"} ",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"dev-prometheus;172.31.93.122\", job=\"aws_sd\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"dev-prometheus;172.31.93.122\", job=\"aws_sd\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"dev-prometheus;172.31.93.122\", job=\"aws_sd\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"aws_sd\",instance=\"dev-prometheus;172.31.93.122\"}[5m])",
     "legendFormat": "{{device}}receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"aws_sd\",instance=\"dev-prometheus;172.31.93.122\"}[5m])",
     "legendFormat": "{{device}}transmit"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"aws_sd\",instance=\"dev-prometheus;172.31.93.122\", device!~\"/dev/loop.*\", device!~\"tempfs | nsfs\", device!=\"gvfsd-fuse\"} - node_filesystem_avail_bytes{job=\"aws_sd\",instance=\"dev-prometheus;172.31.93.122\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}