global:
  scrape_interval: 15s

rule_files:
    - "rules/alerts.yml"
    - "rules/recording_rule.yml"
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['<<<ip>>>:9100']
